drawer_detection_node:
  ros__parameters:
    room_type: "kitchen"
    query: "fork"
    gnn_checkpoint: ""              # GNN checkpoint path (empty = default)
    edge_cutoff: 0.9
    gnn_det_min_score: 0.8
